account_mapping:
  - pattern: "^Account Name 1"
    parser: BillParserA

description_mapping:
  "^TAX": "Taxes"
  "TAXES": "Taxes"
  "Property Tax": "Taxes"
  "grocery store": "Groceries"
  "market": "Groceries"
