account_mapping:
  - pattern: "^Account Name 1"
    parser: BillParserA

description_mapping:
  - category: "Taxes"
    patterns:
      - "^TAX"
      - "TAXES"
      - "Property Tax"
  - category: "Groceries"
    patterns:
      - "grocery store"
      - "market"
